# Generated by Django 4.2.16 on 2024-10-18 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_alter_movie_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
